FROM node:20-alpine

WORKDIR /app

# Most már nem az "app/" mappából, hanem a gyökérből másolunk!
COPY package*.json ./

RUN npm install

# Itt is: a teljes jelenlegi mappát (gyökér) másoljuk a konténerbe
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]