import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Egyszerű skeleton: hagyjuk a rendszer betűtípust (kompatibilis Next.js 14-ben is).
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
